apiVersion: v1
kind: Service
metadata:
  name: heimdall-loadBalancer
  namespace: default
  # annotations:
    # Optional: If you were to use an external LoadBalancer like MetalLB
    # metallb.universe.tf/address-pool: my-app-pool
    # metallb.universe.tf/allow-shared-ip: app-svc
spec:
  selector:
    app: heimdall
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
