apiVersion: v1
kind: Service
metadata:
  name: heimdall-externalip
spec:
  selector:
    name: heimdall
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  externalIPs:
    - 10.0.100.30

